In [1]:
import torch
from torch import nn 
from torch.nn import functional as F
from d2l import torch as d2l

In [3]:
# we construct a layer without parameters, it simply subtracts the mean from its input
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [4]:
layer = CenteredLayer()
layer(torch.tensor([1.0, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [5]:
# we can now use this layer as a component in constructing more complex models
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())

/Users/luisali/miniconda3/envs/d2l/lib/python3.9/site-packages/torch/nn/modules/lazy.py:178: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [6]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(7.9162e-09, grad_fn=<MeanBackward0>)

In [7]:
# defining layers with parameters
# we use built-in functions to create parameters, which means we don't have to define everything for everything
class MyLinear(nn.Module):

    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [8]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.1585, -0.0569, -0.6039],
        [-0.0123,  0.3269, -0.6729],
        [ 1.3687,  1.0905, -0.5045],
        [ 0.3837,  1.4737,  0.2647],
        [-0.4126,  0.6453, -0.1818]], requires_grad=True)

In [9]:
linear(torch.rand(2, 5))

tensor([[1.4264, 1.8277, 0.0000],
        [1.2827, 1.6700, 0.0000]])

In [11]:
# we can use our custom layers just like the built-in fully connected layer
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[1.4608],
        [5.5145]])